### ISSUE TITLE
small fps

### ISSUE THREAD

**Issue by Timon2033** [rosimildo/videoenc#5]
why fps is so small? i try 
`./videoenc -i /dev/video0 -r 30 -q 36,42 -s 640x480 -o /tmp/out1.h264`
and i get 
'frames/sec: 21`

but when i use 320x240 i have
`frames/sec: 42`

How can i increase fps?(i use allwiner h3 on nanopi air board and usb webcam wich support mjpeg and yuyv422 format)

**Comment by rosimildo** [comment]
Usually the fps is limited by the video source ( /dev/video0 ). You can use ffmpeg or other tool to find what is the FPS for your camera.

The encoder can't take MJPEG as source.
