### ISSUE TITLE
fps always 119 and video slow motion

### ISSUE THREAD

**Issue by AtonWu** [rosimildo/videoenc#6]
Hi rosimildo, i have two problems, could you help me?

the first is what ever i try

./videoenc -i /dev/video0 -r 30 -s 1920x1080 -o /out1.h264

or

./videoenc -i /dev/video0 -r 60 -s 1920x1080 -o /out1.h264

but the frames/sec: always 119

and the out1.h264 video get slomotion, it need to speed up 2x, to get normal video.

i use allwiner a83t and a camera wich support h264 1080p 60fps and yuv420 format

could give me a hand, thanks a lot,

**Comment by rosimildo** [comment]
The "BLOBS" from Allwinner on this project is for H3 family. I don't have A83t hardware, and I assume it won't work. A patch or a note indicating something would be helpful!

**Comment by rosimildo** [comment]
I am closing the issue, since this H/W is not supported.
