### ISSUE TITLE
Color is off in H.264 video

### ISSUE THREAD

**Issue by hellochenwang** [rosimildo/videoenc#7]
Hi,

Thanks for sharing the great work! I'm able to encode videos to H.264 through hardware encoder. Although I noticed in the H.264 video, the color is a bit off, it's like watching a 3D video without the 3D glasses. It looks like this:
![image](https://user-images.githubusercontent.com/16633061/28735372-b68e3544-7399-11e7-9e64-37203c465e81.png)

The original YUV420 video looks like this:
![image](https://user-images.githubusercontent.com/16633061/28735427-e7b2707c-7399-11e7-87b0-ac3b94ea90d9.png)

Here are the steps I took to convert the sample video:

- 1. wget http://trace.eas.asu.edu/yuv/stefan/stefan_cif.7z
- 2. 7zr e stefan_cif.7z
- 3. cat stefan_cif.yuv | ./videoenc -s 352x288 -o a.h264

What might be wrong?

**Comment by rosimildo** [comment]
I would try to experiment with the PIXEL_FORMATS ( see encoder.h ).

The Pixel format is hardcoded,  and maybe you could try this: VENC_PIXEL_YUV420P

I don't have a working H3 system at the moment to try out.

Change the file: videoenc.cpp, line ~~ 521
from:
baseConfig.eInputFormat = VENC_PIXEL_YUV420SP;
to:
baseConfig.eInputFormat = VENC_PIXEL_YUV420P;

I believe this solves it. 

Rosimildo

**Comment by rosimildo** [comment]
I have fixed the issue and closed this issue.
