### ISSUE TITLE
Any benchmarks on fps?

### ISSUE THREAD

**Issue by jlee167** [rosimildo/videoenc#8]
No issue, just a question.
Do you have any rough idea about max capability of this encoder? (I'm using Orange Pi PC)
I could only test up to 800x600 because of lack of proper video source. (I'm working on it)
Do you have any rough idea to what resolution I get to at stable 30fps?
I know that datasheet says 1080p30 encoding, but I could only get 30fps at 800x600,  so I'm a little bit worried.

**Comment by rosimildo** [comment]
Jlee167, 
I have not tested with many sources and resolution either. I used with the Marsboard, TVIN at 24FPS 800x600 and was able to sustain 24fps, with very low CPU activity.  I tested with some USB sources, but the limiting factor was the USB sub-system. I moved on to other things, these days and I have not touched it, in years.
